/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/ui/alert/Alert.vue')['default']
    AlertDescription: typeof import('./src/components/ui/alert/AlertDescription.vue')['default']
    AlertTitle: typeof import('./src/components/ui/alert/AlertTitle.vue')['default']
    AuroraBackground: typeof import('./src/components/ui/aurora-background/AuroraBackground.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    CourseCard: typeof import('./src/components/course/CourseCard.vue')['default']
    CourseList: typeof import('./src/components/course/CourseList.vue')['default']
    FilterSection: typeof import('./src/components/course/FilterSection.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InteractiveGridPattern: typeof import('./src/components/ui/interactive-grid-pattern/InteractiveGridPattern.vue')['default']
    LeftMenu: typeof import('./src/components/manage/left-menu.vue')['default']
    LetterPullup: typeof import('./src/components/ui/letter-pullup/LetterPullup.vue')['default']
    LiveTop: typeof import('./src/components/LiveTop.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    PptPage: typeof import('./src/components/PptPage.vue')['default']
    Ripple: typeof import('./src/components/ui/ripple/Ripple.vue')['default']
    RippleCircle: typeof import('./src/components/ui/ripple/RippleCircle.vue')['default']
    RippleContainer: typeof import('./src/components/ui/ripple/RippleContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowPptPage: typeof import('./src/components/ShowPptPage.vue')['default']
    Test: typeof import('./src/components/test.vue')['default']
    WebRTCPlayer: typeof import('./src/components/WebRTCPlayer.vue')['default']
  }
}
