/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '//[courseid]': RouteRecordInfo<'//[courseid]', '/:courseid', { courseid: ParamValue<true> }, { courseid: ParamValue<false> }>,
    '//card': RouteRecordInfo<'//card', '/card', Record<never, never>, Record<never, never>>,
    '/chapter/[chapterid]': RouteRecordInfo<'/chapter/[chapterid]', '/chapter/:chapterid', { chapterid: ParamValue<true> }, { chapterid: ParamValue<false> }>,
    '/chapter/avatar_ai': RouteRecordInfo<'/chapter/avatar_ai', '/chapter/avatar_ai', Record<never, never>, Record<never, never>>,
    '/chapter/avatar_video': RouteRecordInfo<'/chapter/avatar_video', '/chapter/avatar_video', Record<never, never>, Record<never, never>>,
    '/chapter/docs': RouteRecordInfo<'/chapter/docs', '/chapter/docs', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/manage': RouteRecordInfo<'/manage', '/manage', Record<never, never>, Record<never, never>>,
    '/manage/control/': RouteRecordInfo<'/manage/control/', '/manage/control', Record<never, never>, Record<never, never>>,
    '/manage/course/': RouteRecordInfo<'/manage/course/', '/manage/course', Record<never, never>, Record<never, never>>,
    '/manage/course/all': RouteRecordInfo<'/manage/course/all', '/manage/course/all', Record<never, never>, Record<never, never>>,
    '/manage/course/detail': RouteRecordInfo<'/manage/course/detail', '/manage/course/detail', Record<never, never>, Record<never, never>>,
    '/manage/course/student': RouteRecordInfo<'/manage/course/student', '/manage/course/student', Record<never, never>, Record<never, never>>,
  }
}
