/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '//': RouteRecordInfo<'//', '/', Record<never, never>, Record<never, never>>,
    '//[courseid]': RouteRecordInfo<'//[courseid]', '/:courseid', { courseid: ParamValue<true> }, { courseid: ParamValue<false> }>,
    '//card': RouteRecordInfo<'//card', '/card', Record<never, never>, Record<never, never>>,
    '/course/': RouteRecordInfo<'/course/', '/course', Record<never, never>, Record<never, never>>,
    '/live/': RouteRecordInfo<'/live/', '/live', Record<never, never>, Record<never, never>>,
    '/live/[chapterid]': RouteRecordInfo<'/live/[chapterid]', '/live/:chapterid', { chapterid: ParamValue<true> }, { chapterid: ParamValue<false> }>,
    '/live/avatar': RouteRecordInfo<'/live/avatar', '/live/avatar', Record<never, never>, Record<never, never>>,
    '/live/docs': RouteRecordInfo<'/live/docs', '/live/docs', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/manage/': RouteRecordInfo<'/manage/', '/manage', Record<never, never>, Record<never, never>>,
  }
}
